[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace]
resolver = "2"
members = [
  "concurrent_output",
  "it_department",
  "network_simulator",
]

[workspace.dependencies]
phantom_newtype = "0.2"
thiserror = "1.0"
clap = { version = "4", features = ["derive"] }